version: '3'
services:
  db:
    image: postgres:14.4-alpine
    container_name: ${APP_NAME}-db
    environment:
      POSTGRES_DB: ${DB_POSTGRE_DATABASE}
      POSTGRES_USER: ${DB_POSTGRE_USERNAME}
      POSTGRES_PASSWORD: ${DB_POSTGRE_PASSWORD}
    ports:
      - 5432:${DB_POSTGRE_PORT}
    volumes:
      - hk-cp:/var/lib/postgresql/data
    restart: unless-stopped
volumes:
  hk-cp:
